-- Enable UUID generation
create extension if not exists "pgcrypto";

-- ============================================================
-- activities: one row per Garmin cycling activity
-- ============================================================
create table activities (
    id                  uuid primary key default gen_random_uuid(),
    garmin_activity_id  bigint unique not null,
    date                date not null,
    activity_type       text not null default 'cycling',
    name                text,
    duration_seconds    int,
    distance_m          double precision,
    elevation_gain_m    double precision,
    avg_power_w         double precision,
    avg_hr              double precision,
    max_hr              double precision,
    normalized_power_w  double precision,
    tss                 double precision,
    intensity_factor    double precision,
    variability_index   double precision,
    efficiency_factor   double precision,
    pw_hr_ratio         double precision,
    decoupling_pct      double precision,
    raw_data            jsonb,
    created_at          timestamptz not null default now()
);

create index activities_date_idx on activities (date desc);

-- ============================================================
-- health_daily: one row per calendar day — health + fitness metrics
-- ============================================================
create table health_daily (
    id                  uuid primary key default gen_random_uuid(),
    date                date unique not null,
    hrv_ms              double precision,
    resting_hr          double precision,
    sleep_score         double precision,
    sleep_duration_s    int,
    respiratory_rate    double precision,
    max_overnight_hr    double precision,
    pulse_ox            double precision,
    avg_overnight_hr    double precision,
    stress_score        double precision,
    -- derived fitness metrics (computed by metrics.py after each sync)
    ctl                 double precision,   -- chronic training load (42-day EWMA of daily TSS)
    atl                 double precision,   -- acute training load (7-day EWMA)
    tsb                 double precision,   -- form = CTL − ATL
    created_at          timestamptz not null default now()
);

create index health_daily_date_idx on health_daily (date desc);

-- ============================================================
-- goals: user-stated training goals
-- ============================================================
create table goals (
    id          uuid primary key default gen_random_uuid(),
    description text not null,
    goal_type   text not null,  -- e.g. 'power_3min', 'aerobic_base', 'durability'
    target_value double precision,
    is_active   boolean not null default true,
    created_at  timestamptz not null default now()
);

-- ============================================================
-- races: race calendar
-- ============================================================
create table races (
    id           uuid primary key default gen_random_uuid(),
    name         text not null,
    race_date    date not null,
    race_type    text not null,   -- 'Gravel', 'MTB', 'Road'
    distance_km  double precision,
    elevation_m  double precision,
    priority     text not null,   -- 'A', 'B', 'C'
    notes        text,
    created_at   timestamptz not null default now()
);

create index races_date_idx on races (race_date asc);

-- ============================================================
-- availability: minutes available per day of week, per week
-- ============================================================
create table availability (
    id                uuid primary key default gen_random_uuid(),
    week_start        date not null,           -- Monday of the target week
    day_of_week       smallint not null,        -- 0=Mon … 6=Sun
    available_minutes int not null default 0,
    created_at        timestamptz not null default now(),
    unique (week_start, day_of_week)
);

-- ============================================================
-- workouts: planned workouts generated by the rules engine
-- ============================================================
create table workouts (
    id               uuid primary key default gen_random_uuid(),
    planned_date     date not null,
    workout_type     text not null,   -- 'interval', 'endurance', 'recovery', 'rest'
    title            text not null,
    description      text,
    duration_minutes int,
    tss_target       double precision,
    fit_file_path    text,            -- relative path under data/fit/
    completed        boolean not null default false,
    created_at       timestamptz not null default now()
);

create index workouts_date_idx on workouts (planned_date asc);

-- ============================================================
-- notes: daily AI-generated or system notes
-- ============================================================
create table notes (
    id         uuid primary key default gen_random_uuid(),
    date       date not null,
    note_type  text not null default 'ai_review',   -- 'ai_review', 'system', 'user'
    content    text not null,
    created_at timestamptz not null default now()
);

create index notes_date_idx on notes (date desc);
